using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Shared.Tests;
using Xunit;

namespace EventSystem.Tests;

public class StaticEventIncrementalSourceGeneratorTests
{
    private const string ClassText = @"
namespace TestNamespace;

[Generators.Event(typeof(EventHandler))]
public partial struct OnDoStuffEvent
{
}

[Generators.EventHandler]
public partial static class EventHandler
{
}
";
    
    private const string ExpectedGeneratedHandlerClassText = @"// <auto-generated/>

namespace TestNamespace
{
    partial class EventHandler
    {
        public delegate void OnEventRaisedDelegate(Events eventType, IEvent ev);
        public static event OnEventRaisedDelegate OnEventRaised;
        public delegate void OnDoStuffDelegate(TestNamespace.OnDoStuffEvent ev);
        public static event OnDoStuffDelegate OnDoStuff;
        public static event System.Action OnDoStuffNoArgs;
        public static void Raise(TestNamespace.OnDoStuffEvent ev)
        {
            OnEventRaised?.Invoke(Events.OnDoStuff, ev);
            OnDoStuff?.Invoke(ev);
            OnDoStuffNoArgs?.Invoke();
        }
        public enum Events
        {
            OnDoStuff,
        }
        public static void AddListener(Events eventType, System.Action<IEvent> listener)
        {
            switch (eventType)
            {
                case Events.OnDoStuff:
                {
                    OnDoStuffNoArgs += listener;
                    break;
                }
            }
        }
        public static void RemoveListener(Events eventType, System.Action<IEvent> listener)
        {
            switch (eventType)
            {
                case Events.OnDoStuff:
                {
                    OnDoStuffNoArgs -= listener;
                    break;
                }
            }
        }
        public interface IEvent
        {
            Events EventType { get; }
        }
    }
}";
    
    [Fact]
    public void GenerateEventStuff()
    {
        // Create an instance of the source generator.
        var generator = new EventIncrementalSourceGenerator();

        // Source generators should be tested using 'GeneratorDriver'.
        var driver = CSharpGeneratorDriver.Create(generator);

        // We need to create a compilation with the required source code.
        var compilation = CSharpCompilation.Create(nameof(EventIncrementalSourceGenerator),
            new[] { CSharpSyntaxTree.ParseText(ClassText) },
            new[]
            {
                // To support 'System.Attribute' inheritance, add reference to 'System.Private.CoreLib'.
                MetadataReference.CreateFromFile(typeof(object).Assembly.Location)
            });

        // Run generators and retrieve all results.
        var runResult = driver.RunGenerators(compilation).GetRunResult();

        // All generated files can be found in 'RunResults.GeneratedTrees'.
        var generatedHandlerFileSyntax = runResult.GeneratedTrees.Single(t => t.FilePath.EndsWith("EventHandler.g.cs"));
        TestUtils.AssertEqual(ExpectedGeneratedHandlerClassText, generatedHandlerFileSyntax);
    }
}